export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    machineCodexModels: (machineId: string) => ['machine-codex-models', machineId] as const,
    machineClaudeModels: (machineId: string) => ['machine-claude-models', machineId] as const,
    sessionClaudeModels: (sessionId: string) => ['session-claude-models', sessionId] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    sessionCodexModels: (sessionId: string) => ['session-codex-models', sessionId] as const,
    sessionCursorModels: (sessionId: string) => ['session-cursor-models', sessionId] as const,
    sessionCursorChatStore: (sessionId: string) => ['session-cursor-chat-store', sessionId] as const,
    sessionPiModels: (sessionId: string) => ['session-pi-models', sessionId] as const,
    machineCursorModels: (machineId: string) => ['machine-cursor-models', machineId] as const,
    sessionOpencodeModels: (sessionId: string) => ['session-opencode-models', sessionId] as const,
    sessionOpencodeReasoningEffortOptions: (sessionId: string) => ['session-opencode-reasoning-effort-options', sessionId] as const,
    machineOpencodeModelsForCwd: (machineId: string, cwd: string) => ['machine-opencode-models', machineId, cwd] as const,
    machineGrokModelsForCwd: (machineId: string, cwd: string) => ['machine-grok-models', machineId, cwd] as const,
    sessionGrokModels: (sessionId: string) => ['session-grok-models', sessionId] as const,
    sessionGrokReasoningEffortOptions: (sessionId: string) => ['session-grok-reasoning-effort-options', sessionId] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
    skillUsage: ['skill-usage'] as const,
    sessionGroups: ['session-groups'] as const,
}
