import type { AgentState, DecryptedMessage } from '@/types/api'

/**
 * Bump when the fixture document schema or the normative projection changes
 * shape (see shared/fixtures/README.md for the policy). Written verbatim to
 * shared/fixtures/VERSION; native test suites must fail when the on-disk
 * version is newer than the one they support.
 */
export const FIXTURE_VERSION = 1

/**
 * A hand-authored fixture case: wire-shaped inputs only. Everything under
 * `expected` in the emitted document is machine-generated by running the real
 * web chat pipeline over these inputs — never hand-written.
 */
export type FixtureCase = {
    /** Kebab-case name; becomes shared/fixtures/chat/<name>.json */
    name: string
    description: string
    /** Wire messages exactly as delivered by GET /sessions/:id/messages. */
    messages: DecryptedMessage[]
    /** session.agentState at render time (permission requests live here). */
    agentState?: AgentState | null
    options?: {
        /** Older history exists beyond `messages` (affects tool-group identity). */
        hasMoreMessages?: boolean
    }
}

export type FixtureInput = {
    messages: DecryptedMessage[]
    agentState: AgentState | null
    options: { hasMoreMessages: boolean }
}

export type FixtureExpected = {
    blocks: unknown[]
    hasReadyEvent: boolean
    latestUsage: unknown
    visibleBlocks: unknown[]
}

export type FixtureDocument = {
    fixtureVersion: number
    name: string
    description: string
    input: FixtureInput
    expected: FixtureExpected
}

export function toFixtureInput(fixtureCase: FixtureCase): FixtureInput {
    return {
        messages: fixtureCase.messages,
        agentState: fixtureCase.agentState ?? null,
        options: { hasMoreMessages: fixtureCase.options?.hasMoreMessages ?? false }
    }
}
