import type { Session, SessionPatch } from '@/types/api'

/** Per-patch verdict of `applySessionDetailPatch`: `applied` when the call
 *  returned a new session object, `unchanged` when it returned null (keep the
 *  previous object — version-gated, render-irrelevant, or no-op patch). */
export type SessionPatchResult = 'applied' | 'unchanged'

/**
 * A hand-authored SSE session-patch case. `initialSession` and every patch
 * are wire-shaped inputs; the emitted document stores them schema-normalized
 * (`SessionSchema.parse` / `SessionPatchSchema.parse`) and everything under
 * `expected*` is machine-generated by running the real web patch fold
 * (`applySessionDetailPatch`) — never hand-written.
 */
export type SseFixtureCase = {
    /** Kebab-case name; becomes shared/fixtures/sse/<name>.json */
    name: string
    description: string
    /** Full Session as cached before the first patch arrives. */
    initialSession: Session
    /** SessionPatch payloads of `session-updated` events, in arrival order. */
    patches: SessionPatch[]
}

export type SseFixtureDocument = {
    fixtureVersion: number
    name: string
    description: string
    initialSession: Session
    patches: SessionPatch[]
    /** Aligned with `patches`: verdict of each applySessionDetailPatch call. */
    expectedPatchResults: SessionPatchResult[]
    /** Session state after folding all patches. */
    expectedSession: Session
}
